package edu.pjwstk.s19701.model;

public enum Diseases {
    AVIAN_INFLUENZA,
    AUSTRALIAN_BAT_LYSSAVIRUS,
    ANTHRAX,
    AKABANE_DISEASE,
    AFRICAN_SWINE_FEVER,
    AFRICAN_HORSE_SICKNESS,
    AFLATOXICOSIS,
    OTHER
}
